export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const COMPANIES_LOAD_SUCCESS = "COMPANIES_LOAD_SUCCESS";
export const REQUEST_COMPANY_DETAILS = "REQUEST_COMPANY_DETAILS";
export const GET_COMPANY_DETAILS = "GET_COMPANY_DETAILS";

export const SAVE_ORDER = "SAVE_ORDER";
export const SEND_ORDER = "SEND_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const SEND_ORDER_SUCCESS = "SEND_ORDER_SUCCESS";
export const SET_COMPANY = "SET_COMPANY";

export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_MODAL = "SHOW_MODAL";

export const USER_EDIT = "USER_EDIT";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";

export const COMPANY_EDIT = "COMPANY_EDIT";
export const COMPANY_EDIT_SUCCESS = "COMPANY_EDIT_SUCCESS";

export const ORDERS_LOAD_SUCCESS = "ORDERS_LOAD_SUCCESS";
export const ORDERS_REQUEST = "ORDERS_REQUEST";
export const RESET_ORDERS = "RESET_ORDERS";

export const CREATE_REVIEW = "CREATE_REVIEW";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_ERROR = "CREATE_REVIEW_ERROR";
export const GET_COMPANY_REVIEWS = "GET_COMPANY_REVIEWS";
export const GET_COMPANY_REVIEWS_SUCCESS = "GET_COMPANY_REVIEWS_SUCCESS";
export const RESET_COMPANY_REVIEWS = "RESET_COMPANY_REVIEWS";
export const OPEN_REVIEW_MODAL = "OPEN_REVIEW_MODAL";
export const HIDE_REVIEW_MODAL = "HIDE_REVIEW_MODAL";
